# Generated by Django 4.1.4 on 2022-12-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_epic',
            field=models.BooleanField(default=False),
        ),
    ]
