# Generated by Django 4.1.4 on 2022-12-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_steamID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
