# Generated by Django 4.1.4 on 2022-12-20 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_wishlist_user_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_name',
            new_name='wishlist_game_name',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_steamID',
            new_name='wishlist_game_steamID',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='id',
            new_name='wishlist_item_id',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='wishlist_owner',
        ),
    ]
