# Generated by Django 4.1.4 on 2022-12-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_wishlist_name_wishlist_wishlist_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_game_gameID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
