# Generated by Django 4.1.4 on 2022-12-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='addedBy',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
